---
- name: playbook for  user create
  hosts: all
  become: no
  vars_files: 
    - user_list.yml
  vars: 
    password: "{{ lookup('password', './{{ item.name }}-password length=15')}}"
  tasks:
    - name: user create
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        state: present
        password: "{{ password|password_hash('sha512')}}"
        comment: "{{ item.first|capitalize }} {{ item.middle|capitalize }} {{ item.last|capitalize }}"
        update_password: on_create
      with_items: "{{ users }}"
